/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/carte': RouteRecordInfo<'/carte', '/carte', Record<never, never>, Record<never, never>>,
    '/exports': RouteRecordInfo<'/exports', '/exports', Record<never, never>, Record<never, never>>,
    '/imports': RouteRecordInfo<'/imports', '/imports', Record<never, never>, Record<never, never>>,
    '/lexique': RouteRecordInfo<'/lexique', '/lexique', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/ogs': RouteRecordInfo<'/ogs', '/ogs', Record<never, never>, Record<never, never>>,
    '/parametres': RouteRecordInfo<'/parametres', '/parametres', Record<never, never>, Record<never, never>>,
    '/point-detail': RouteRecordInfo<'/point-detail', '/point-detail', Record<never, never>, Record<never, never>>,
    '/points': RouteRecordInfo<'/points', '/points', Record<never, never>, Record<never, never>>,
    '/profil': RouteRecordInfo<'/profil', '/profil', Record<never, never>, Record<never, never>>,
    '/projets/': RouteRecordInfo<'/projets/', '/projets', Record<never, never>, Record<never, never>>,
    '/projets/[id]': RouteRecordInfo<'/projets/[id]', '/projets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/qrcodes': RouteRecordInfo<'/qrcodes', '/qrcodes', Record<never, never>, Record<never, never>>,
    '/utilisateurs': RouteRecordInfo<'/utilisateurs', '/utilisateurs', Record<never, never>, Record<never, never>>,
    '/zones/': RouteRecordInfo<'/zones/', '/zones', Record<never, never>, Record<never, never>>,
    '/zones/edit': RouteRecordInfo<'/zones/edit', '/zones/edit', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/carte.vue': {
      routes: '/carte'
      views: never
    }
    'src/pages/exports.vue': {
      routes: '/exports'
      views: never
    }
    'src/pages/imports.vue': {
      routes: '/imports'
      views: never
    }
    'src/pages/lexique.vue': {
      routes: '/lexique'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/ogs.vue': {
      routes: '/ogs'
      views: never
    }
    'src/pages/parametres.vue': {
      routes: '/parametres'
      views: never
    }
    'src/pages/point-detail.vue': {
      routes: '/point-detail'
      views: never
    }
    'src/pages/points.vue': {
      routes: '/points'
      views: never
    }
    'src/pages/profil.vue': {
      routes: '/profil'
      views: never
    }
    'src/pages/projets/index.vue': {
      routes: '/projets/'
      views: never
    }
    'src/pages/projets/[id].vue': {
      routes: '/projets/[id]'
      views: never
    }
    'src/pages/qrcodes.vue': {
      routes: '/qrcodes'
      views: never
    }
    'src/pages/utilisateurs.vue': {
      routes: '/utilisateurs'
      views: never
    }
    'src/pages/zones/index.vue': {
      routes: '/zones/'
      views: never
    }
    'src/pages/zones/edit.vue': {
      routes: '/zones/edit'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
